Game 43
chap0lin/dom-que-shot pull request #11
Opened 2022-10-26 23:25 UTC by AmigoDoCarlos

> Estabelecimento de conexão com o servidor no lobby, update em tempo real dos usuários na sala, suporte a várias salas
> pequena correção na visibilidade do aviso de sala inválida (arquivo home.tsx)

2022-10-27 17:08 UTC, RSinhoroto approved these changes

2022-10-28 15:49 UTC, chap0lin requested changes
Acho que o único problema é com o conflito de implementações de singleton. Acho que tu resolves tudo isso:

- apagando a linha 10 do socket.ts
- o teu export de socket.ts deveria ser só a classe e não uma instancia.
- na linha 57 do socket.ts adiciona um static antes da definição da função.
- Atualiza os imports e uso no BangBang e no Lobby.

2022-10-28 15:49 UTC, chap0lin commented on src/lib/socket.ts
> +const socketConnection = new SocketConnection();
Podemos deixar assim por enquanto, mas não me agrada muito código sendo executado como side effect de uma importação. Nesse caso, na hora que o primeiro componente importar (usando ou não) essa conexão de socket será criada.

2022-10-28 15:49 UTC, chap0lin commented on src/lib/socket.ts
> +      SocketConnection.instance = this;
Outra maneira de fazer o singleton né, acho que temos que bater o martelo aqui, ou usa assim ou usa o getInstance(). Não é legal ficar fazendo de um jeito em um lugar de outro jeito noutro.

2022-10-28 18:34 UTC, AmigoDoCarlos commented on src/lib/socket.ts
> +const socketConnection = new SocketConnection();
eu eliminei o construtor e reservei o código dele em uma função separada 'connect()'. Agora nada é executado como side effect, somente quando chamamos a função. Espero que tenha servido.

2022-10-28 18:36 UTC, AmigoDoCarlos commented on src/lib/socket.ts
> +      SocketConnection.instance = this;
eu alterei para ficar só no 'getInstance()'. Acredito estar mais padronizado agora. A forma que tinha feito antes estava de acordo com o que vi em videoaulas.

2022-10-28 18:37 UTC, chap0lin approved these changes
Perfeito!

2022-10-28 18:41 UTC, merged