[GAME 67] Added working create room path
chap0lin/dom-que-shot pull request #17
Opened 2022-11-20 12:03 UTC by RSinhoroto

2022-11-20 12:17 UTC, chap0lin requested changes
Parece bom, só ajustar alguns pontos.

2022-11-20 12:17 UTC, chap0lin commented on src/lib/socket.ts
> +    console.log('ENTROU AQUI!!!')
🧹

2022-11-20 12:17 UTC, chap0lin commented on src/scenes/Home/Home.tsx
> +        // error handling
Coloca pelo menos um alert aqui. `alert("Erro ao criar a sala"`).

2022-11-20 12:17 UTC, chap0lin commented on src/scenes/Lobby/Lobby.tsx
> +import api from '../../services/api';
Tá usando isso aqui?

2022-11-20 12:17 UTC, chap0lin commented on src/scenes/Lobby/Lobby.tsx
> +    //TODO: não deixar o usuário entrar em uma sala que não existe (não está mais na instância do Store)
Nesse caso o joinRoom vai falhar.

![image](https://user-images.githubusercontent.com/15856499/202901364-83c6febc-89d1-4399-8977-8721ab6b9343.png)

Só tem que lidar com a resposta.

2022-11-21 23:14 UTC, RSinhoroto commented on src/lib/socket.ts
> +    console.log('ENTROU AQUI!!!')
Agora eu lembrei porque não tinha feito o pull request 😅

2022-11-21 23:16 UTC, RSinhoroto commented on src/scenes/Lobby/Lobby.tsx
> +import api from '../../services/api';
Tá não, retirei

2022-11-22 00:12 UTC, Luiza-cm approved these changes

2022-11-22 00:16 UTC, merged