Game 47
chap0lin/dom-que-shot pull request #18
Opened 2022-11-21 18:52 UTC by Luiza-cm

Nessa atividade foi implementado o frontend/design do jogo BangBang, de maneira que ele esteja totalmente funcional. Foi feita a refatoração das rotas,  animação de início de jogo, etc.
Para testar, você precisará utilizar pelo menos 2 abas do navagador, entrar na sala "1", colocar seu nome/apelido e escolher o avatar; em seguida retorne para a página inicial do jogo e então clique na área com o carrossel de jogos, e depois clique em BangBang.

2022-11-21 22:33 UTC, chap0lin commented on src/routes.tsx
> +import BangBang from './scenes/BangBang';
🧹

2022-11-21 22:51 UTC, chap0lin requested changes
Tem uma imagem desnecessária que não usas "drinks-background.png".
Outra imagem: "title-bangbang.png".
Roda lint e format por favor, tem muita coisa declarada não sendo utilizada (Ex: Ingo/index.tsx - linhas 2, 3, 4 e 5.

2022-11-21 22:51 UTC, chap0lin commented on src/routes.tsx
> +import BangBang from './scenes/BangBang';
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/Home/Home.tsx
> +    navigate('/ChooseAvatar', {
Isso não pode subir, quando abrir um PR assim, marca um TODO aqui pelo menos pra lembrar de remover antes de dar o merge.

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Cover/index.tsx
> +            {/* <p className="cover-title">{title}</p> */}
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Cover/index.tsx
> +import gsap from "gsap";
tá usando isso aqui? 🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Game/BangBang.css
> +  /* z-index: -1; */
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Info/Info.css
> +/* .container-header {
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Info/Info.css
> +.content {
esses estilos nomeados desse jeito são perigosos, precisamos lembrar que os imports do css são globais. Define um nome mais específico pra essa classe ou envelopa com um div com id e corrige essas referencias.

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Ranking/Ranking.css
> +.container-header {
mesma coisa pros estilos aqui, coloca o #ranking-page antes de tudo isso.

2022-11-21 22:51 UTC, chap0lin commented on src/Components/RankingItem/index.tsx
> +interface RankingItemProps {
Dá um enter entre os imports e o resto do código.

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Ranking/index.tsx
> +import { Link } from "react-router-dom";
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Info/index.tsx
> +import titleImage from '../../../assets/BangBang/title-bangbang.png';
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Game/index.tsx
> +import { RankingPage } from '../Ranking';
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/Game/index.tsx
> +  const [deadline, setDeadline] = useState(false);
Acabou que a gente não tá explicitamente usando esse deadline pra nada né? Então acho que pode remover, vê se quebra alguma coisa.

2022-11-21 22:51 UTC, chap0lin commented on src/Components/Header/index.tsx
> +import React, { useState } from 'react';
Essas alterações daqui são só as que o Alex já tinha feito né? Prestar atenção na hora do merge só pra garantir que não quebra nada na solução dos conflitos.

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/BangBang.tsx
> +const players = [
Esses players mockados não estão mais sendo utilizados né?
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/BangBang.tsx
> +    // socketConn.joinRoomWithCode(bangBangRoom);//// atuar em cima disso
🧹

2022-11-21 22:51 UTC, chap0lin commented on src/scenes/BangBang/BangBang.tsx
> +          //coverPage={() => setCurrentGameState(Game.Cover)}
🧹

2022-11-22 01:21 UTC, RSinhoroto approved these changes

2022-11-22 01:36 UTC, merged