Ajustes finais e inclusão dos jogos restantes
chap0lin/dom-que-shot pull request #27
Opened 2022-12-01 23:25 UTC by AmigoDoCarlos

Componentização dos jogos de cartas simples.
Componentização da tela de capa (cover).
Componentização da tela de informação (info).

Novos ajustes em commits seguintes.

2022-12-01 23:51 UTC, chap0lin requested changes
Só aguardando as alterações do owner e jogador da vez.

2022-12-01 23:51 UTC, chap0lin commented on src/Components/Game/Info/index.tsx
> +        <Button>
Mano, coloca onclick no botão para de encher de div.

2022-12-01 23:51 UTC, chap0lin commented on src/scenes/BangBang/BangBang.tsx
> +          // turnVisibility={turnVisibility}
colocar o TODO aqui também pra não esquecer

2022-12-01 23:51 UTC, chap0lin commented on src/scenes/OEscolhido/OEscolhido.tsx
> +          //turnVisibility={turnVisibility}
aqui também

2022-12-01 23:51 UTC, chap0lin commented on src/scenes/Vrum/Vrum.tsx
> +  const info = (
pode ser description agora né, já que é o nome que estás usando mais pra frente.

2022-12-01 23:54 UTC, AmigoDoCarlos commented on src/Components/Game/Info/index.tsx
> +        <Button>
ow kkk esqueci desse detalhe, perdão

2022-12-01 23:58 UTC, AmigoDoCarlos commented on src/scenes/Vrum/Vrum.tsx
> +  const info = (
ook

2022-12-01 23:58 UTC, AmigoDoCarlos commented on src/scenes/OEscolhido/OEscolhido.tsx
> +          //turnVisibility={turnVisibility}
ook

2022-12-01 23:58 UTC, AmigoDoCarlos commented on src/scenes/BangBang/BangBang.tsx
> +          // turnVisibility={turnVisibility}
ook

2022-12-07 18:26 UTC, chap0lin approved these changes
Tá bão, corrige esses detalhes que eu pontuei e pode dar merge.

2022-12-07 18:26 UTC, chap0lin commented on src/scenes/BangBang/BangBang.tsx
> +      Inciada a partida, todos os jogadores devem atirar no alvo dentro do tempo
Iniciada**

2022-12-07 18:26 UTC, chap0lin commented on src/scenes/BangBang/BangBang.tsx
> +          coverImg: coverImg,
Por que a gente passa esse coverImg aqui mesmo? Me responde lá no slack pls

2022-12-07 18:26 UTC, chap0lin commented on src/scenes/DireitaEsquerda/DireitaEsquerda.tsx
> +export default function DireitaEsquerda() {
Vamos remover esse da lista por enquanto, depois que adicionarmos o dado a gente volta com ele.

2022-12-07 18:26 UTC, chap0lin commented on src/scenes/SelectNextGame/SelectNextGame.tsx
> +    text: 'Direita-Esquerda',
aqui e lá no adega.

2022-12-07 18:26 UTC, chap0lin commented on src/Components/Game/SimpleCardGame/SimpleCardGame.tsx
> +import socketConnection from '../../../lib/socket';
Importa e usa com o S maiusculo, quando usamos o s minusculo parece que é uma instancia, e a gente só pega a instancia quando a gente chama a função get Instace lá. Dá um ctrl+shift+f e troca onde tiver socketConnection por SocketConnection.

2022-12-07 18:26 UTC, chap0lin commented on src/Components/Game/SimpleCardGame/SimpleCardGame.tsx
> +      );
pode remover esse default.

2022-12-08 21:19 UTC, AmigoDoCarlos commented on src/scenes/DireitaEsquerda/DireitaEsquerda.tsx
> +export default function DireitaEsquerda() {
done

2022-12-08 21:20 UTC, AmigoDoCarlos commented on src/scenes/SelectNextGame/SelectNextGame.tsx
> +    text: 'Direita-Esquerda',
done. Criei um PR específico no backend.

2022-12-08 21:22 UTC, AmigoDoCarlos commented on src/Components/Game/SimpleCardGame/SimpleCardGame.tsx
> +import socketConnection from '../../../lib/socket';
certo, fiz a modificação

2022-12-08 21:24 UTC, AmigoDoCarlos commented on src/Components/Game/SimpleCardGame/SimpleCardGame.tsx
> +      );
certo

2022-12-08 21:36 UTC, merged