adicionada informação pop-up dos jogos na tela de Home
chap0lin/dom-que-shot pull request #33
Opened 2022-12-12 20:52 UTC by AmigoDoCarlos

Neste PR:
> Adicionadas informações dos jogos na tela de Home. As informações aparecem como uma janela pop-up quando o usuário aperta nos cards dos jogos.
>Atualizados os jogos dos cards. Remoção do jogo 'Roleta', que não existe no aplicativo.

2022-12-15 22:51 UTC, chap0lin reviewed
Esse asset Wrong.png não pode ser substituido pelo X do react-feather?

2022-12-15 23:26 UTC, chap0lin approved these changes
Tá bom, mas acho que dá pra fazer uns pequenos ajustes pra melhorar. Deixei algumas perguntas também, em especial aquele screenDiv me incomoda.

2022-12-15 23:26 UTC, chap0lin commented on src/scenes/Home/Home.css
> +}
Pra que isso? o background já não resolve isso ai?

2022-12-15 23:26 UTC, chap0lin commented on src/scenes/Home/Home.tsx
> +    <div className="ScreenDiv">
!

2022-12-15 23:26 UTC, chap0lin commented on src/scenes/Home/Home.tsx
> +  const [gameDescription, setGameDescription] = useState('');
Une isso num estado só, não precisa de 2 estados se eles estão sempre associados. Cria um tipo que possui titulo e content e faz 1 estado só desse tipo, aí passa só um setState pro imageSlider.

2022-12-19 18:44 UTC, AmigoDoCarlos commented on src/scenes/Home/ImageSlider/index.tsx
> +    description: string;
vale sim

2022-12-19 20:03 UTC, AmigoDoCarlos commented on src/scenes/Home/Home.tsx
> +  const [gameDescription, setGameDescription] = useState('');
feito

2022-12-19 20:04 UTC, AmigoDoCarlos commented on src/scenes/Home/Home.css
> +}
Não resolve. Consegui fazer o popup funcionar sem esse div, mas estou com dificuldades em alinhar o cotneúdo na tela.

2022-12-22 01:03 UTC, chap0lin requested changes

2022-12-22 01:03 UTC, chap0lin commented on src/Components/Background/Background.css
> +  height: 100vh;
muito perigoso isso. com o overflow hidden ainda. o Background é usado em quase todas as telas e dessa maneira não vamos permitir que nenhuma delas tenha conteúdo superior a 100vh em nenhum tamanho de tela.

2022-12-22 01:03 UTC, chap0lin commented on src/scenes/Welcome/Welcome.tsx
> +  //window.history.replaceState({}, 'Dom Que Shot!', 'http://localhost:5173'); //TODO uncomment this when tests are over
Lembrar de tirar daqui.

2022-12-23 12:40 UTC, chap0lin approved these changes

2022-12-23 14:25 UTC, merged