Game 110 - Padronização da posição do botão principal e outros ajustes
chap0lin/dom-que-shot pull request #54
Opened 2023-01-23 21:11 UTC by AmigoDoCarlos

Neste PR:

> Os botões principais de todas as telas aplicáveis (roleta, lobby, capa dos jogos, resultados, etc) agora ficam em uma distância padrão de 40px da borda inferior da tela.
> Criado componente BottomButton, que é o botão regular só que contido dentro de uma flexbox. Ele substituiu todos os botões regulares para os ajustes do primeiro item.
> As telas de Lobby, Roleta e capas dos jogos tiveram problemas de responsividade corrigidos.
> As capas dos jogos agora são arquivos de definição mais alta e sem marcas d'água.
> A tela de capa dos jogos agora tem estilização baseada no emotion/styled ao invés do CSS. 

Bugs conhecidos:

>Nenhum.

2023-01-26 22:23 UTC, chap0lin requested changes
Precisas trocar o nome dos arquivos de estilo.
`[COMPONENTE].style.ts`

Outro detalhe, o ideal é a gente usar media queries ou o js dentro do componente para pegar os valores de window. O motivo disso é que quando o componente é renderizado novamente pegamos novos valores para o tamanho da window, o que permite ajustar a tela no caso da janela ser redimensionada. Do jeito feito, hardcoded acaba que ele só pega o tamanho da window 1x quando o arquivo é carregado e é isso. Não apresenta a mesma responsividade que um media query.

2023-01-26 22:23 UTC, chap0lin commented on src/Components/Roulette/RouletteCard/index.tsx
> +  const imageStyle = {
mesma coisa aqui

2023-01-26 22:23 UTC, chap0lin commented on src/Components/Game/Cover/index.tsx
> +  useLayoutEffect(() => {
Boaa!!

2023-01-30 18:17 UTC, AmigoDoCarlos commented on src/Components/Button/index.tsx
> +    <RegularButton onClick={onClick} style={buttonStyle} disabled={isDisabled}>
é exatamente esse o caso. O width e o height têm um valor padrão que é sobrescrito caso o usuário assim deseje fazê-lo ficar de tamanho diferente.

2023-01-30 18:23 UTC, AmigoDoCarlos commented on src/Components/Button/BottomButton/index.tsx
> +  padding: 0 0 40px 0;
done

2023-01-30 19:05 UTC, AmigoDoCarlos commented on src/Components/GameCard/GameCard.ts
> +  width: 90%;
sim, mas a propriedade object-fit: scale-down dispensa a necessidade de declarar ambos. Definir o height também em 90% não vai ter efeito na prática.

2023-01-30 20:18 UTC, AmigoDoCarlos commented on src/Components/GameCard/index.tsx
>        style={{ background: backgroundColor }}>
certo

2023-01-30 20:19 UTC, AmigoDoCarlos commented on src/Components/Placeholder/Image/index.tsx
> +    <Image style={divStyle}>
ok. Eu estou com alguma dificuldade em 'passar a lógica' para dentro dos styled components. Possivelmente precisarei de orientação.

2023-01-30 20:20 UTC, AmigoDoCarlos commented on src/Components/Roulette/index.tsx
> +      <UpperDetail style={detailStyle} />
certo

2023-02-06 21:34 UTC, chap0lin commented on src/scenes/OEscolhido/Game/index.tsx
> +          margin="0 auto 40px auto"
opa

2023-02-06 22:22 UTC, chap0lin approved these changes

2023-02-08 14:32 UTC, merged