GAME-26 (Tela Join)
chap0lin/dom-que-shot pull request #6
Opened 2022-10-11 19:22 UTC by AmigoDoCarlos

> adicionados componentes Button e Header para facilitar implementações futuras. As telas já existentes no projeto foram alteradas de modo a usar estes novos componentes.

> corrigido o box-sizing do projeto como um todo (arquivo src/index.css), que antes estava levando a problemas de dimensionamento dos elementos renderizados.

> correções menores nos arquivos para integrar as mudanças acima.

2022-10-15 19:53 UTC, chap0lin requested changes

2022-10-15 19:53 UTC, chap0lin commented on package.json
> +    "@dicebear/avatars-avataaars-sprites": "^4.10.5",
Remover já que estamos usando o adventurer.

2022-10-15 19:53 UTC, chap0lin commented on src/routes.tsx
>          <Route path="/CreateRoom" element={<CreateRoom />} />
Já que vamos usar só um, vamos de JoinRoom ao invés de CreateRoom.

2022-10-15 19:53 UTC, chap0lin commented on src/scenes/ChooseAvatar/ChooseAvatar.tsx
> +              <div onClick={saveOnLocalStorage}>{buttonText}</div>
Vamos usar esse click aqui para salvar as informações relevantes no localStorage e navegar para a tela do saguão, passando como parametro o option (se ta criando ou entrando). Daí na depois. na próxima tela a gente pode pegar os dados pelos props de navegação ou pegar do localStorage pra criar a conexão do socket.

2022-10-15 19:53 UTC, chap0lin commented on src/scenes/Home/Home.tsx
> +    //console.log("Nenhum código de sala inserido, impossível prosseguir.");
🧹

2022-10-15 19:53 UTC, chap0lin commented on src/scenes/Home/Home.tsx
> +        <div className="JoinRoomWarningSpace">
Podemos seguir com esse erro em cima, qualquer coisa a gente só muda de posição depois.

2022-10-15 19:53 UTC, chap0lin commented on src/scenes/Tutorial/Tutorial.css
> +/* apagar se o componente Button for realmente
🧹

2022-10-15 19:59 UTC, AmigoDoCarlos commented on package.json
> +    "@dicebear/avatars-avataaars-sprites": "^4.10.5",
done

2022-10-15 20:13 UTC, AmigoDoCarlos commented on src/routes.tsx
>          <Route path="/CreateRoom" element={<CreateRoom />} />
ok dokey

2022-10-15 20:15 UTC, AmigoDoCarlos commented on src/scenes/ChooseAvatar/ChooseAvatar.tsx
> +              <div onClick={saveOnLocalStorage}>{buttonText}</div>
isso foi só um comentário ou você quis sugerir uma mudança? kkkk

2022-10-15 20:16 UTC, AmigoDoCarlos commented on src/scenes/Home/Home.tsx
> +    //console.log("Nenhum código de sala inserido, impossível prosseguir.");
diga aonde você vai

2022-10-15 20:17 UTC, AmigoDoCarlos commented on src/scenes/Home/Home.tsx
> +        <div className="JoinRoomWarningSpace">
ok dokey

2022-10-15 20:17 UTC, AmigoDoCarlos commented on src/scenes/Tutorial/Tutorial.css
> +/* apagar se o componente Button for realmente
que eu vou varrendo

2022-10-17 14:22 UTC, chap0lin approved these changes

2022-10-17 14:32 UTC, merged