Game 111 jogo da verdade
chap0lin/dom-que-shot pull request #69
Opened 2023-02-24 13:20 UTC by Luiza-cm

Jogo da Verdade: o jogador deve responder alguma das perguntas que aparecer na tela, e caso não queira, bebe 2x.
A estrutura do código foi feita tendo como base o jogo do Eu nunca.
Vídeo demonstração enviado no zap.

2023-02-27 18:44 UTC, AmigoDoCarlos commented on src/scenes/JogoDaVerdade/Game/Game.style.ts
> +import styled from '@emotion/styled';
ué kkkk então tá usando as duas estilizações?

2023-02-27 18:52 UTC, AmigoDoCarlos requested changes
Achei no geral OK, mas tenho observações:
1. A estilização CSS me parece não estar sendo usada, já que tem um styled component para o mesmo arquivo. Acredito que faltou tirá-la do código; e
2. O PR das variáveis globais mudou a lógica de seleção das telas. Acredito que talvez seja melhor mergeá-lo primeiro e trazer as mudanças dele para cá antes de seguir com este. Mas fazer o contrário não vai gerar muito retrabalho, então fica a critério de vocês.

2023-02-28 11:20 UTC, Luiza-cm commented on src/scenes/JogoDaVerdade/Game/Game.style.ts
> +import styled from '@emotion/styled';
Opa esqueci de tirar os arquivos css kkkkkkk

2023-03-24 23:19 UTC, chap0lin requested changes
Um pouco estranho a gente estar traduzindo tudo para o ingles no codigo e o nome do jogo e dos arquivos ficarem como jogodaverdade. Até as classes css que tu tinhas dado que agora viraram nome de componente estão como TruthGame. Talvez vale a pena só mudar o nome dos componentes mesmo e deixar o jogodaverdade em portugues como os outros jogos (eu nunca, o escolhido, ...)

Precisa rodar o format e o lint só pra garantir.

2023-03-24 23:19 UTC, chap0lin commented on src/scenes/JogoDaVerdade/Game/index.tsx
> +  TruthGameVoteButton
Agora que estamos usando styled-components os nomes não precisam mais herdar o nome do jogo que eles estão inseridos. Pode deixar assim mas saiba que não tem problema chamar de `AwaitingMessage `ao invés de `TruthGameAwaitingMessage`.

2023-03-24 23:19 UTC, chap0lin commented on src/scenes/JogoDaVerdade/JogoDaVerdade.tsx
> +import { useNavigate, useLocation } from 'react-router-dom';
useLocation não é usado

2023-03-24 23:19 UTC, chap0lin commented on src/scenes/JogoDaVerdade/JogoDaVerdade.tsx
> +import Background from '../../components/Background';
Background também não.

2023-03-24 23:19 UTC, chap0lin commented on src/scenes/JogoDaVerdade/JogoDaVerdade.tsx
> +    socket.addEventListener('show-suggestions', (suggs) => {
Esse suggs aqui não é usado pra nada já que as sugestões são guardadas no primeiro momento. Então pode deixar essa função sem prop.
`socket.addEventListener('show-suggestions', () => {`

2023-03-24 23:19 UTC, chap0lin commented on src/scenes/JogoDaVerdade/JogoDaVerdade.tsx
> +  const [JogoDaVerdadeSuggestions, setJogoDaVerdadeSuggestions] = useState<string[]>([]);
poderia ser só suggestions aqui não? não precisa do JogoDaVerdade na frente.

2023-03-25 15:51 UTC, chap0lin approved these changes

2023-03-25 16:31 UTC, AmigoDoCarlos approved these changes

2023-03-25 16:31 UTC, merged