Game XXX - Titanic
chap0lin/dom-que-shot pull request #70
Opened 2023-03-07 16:54 UTC by AmigoDoCarlos

Neste PR:

> Inclusão do jogo Titanic.

Bugs conhecidos:

> Nenhum (glória).

2023-03-07 21:32 UTC, RSinhoroto approved these changes

2023-03-18 01:38 UTC, chap0lin requested changes

2023-03-18 01:38 UTC, chap0lin commented on src/scenes/Titanic/components/Map/Sector/FinishMapSector/index.tsx
> +        element = <ElementIcon key={index + 26} src={iceberg} />;
esses key são necessários aqui? não me parece que esse parâmetro é usado.

2023-03-18 01:38 UTC, chap0lin commented on src/scenes/Titanic/components/Map/Sector/GameMapSector/index.tsx
> +    number >= 100 ? <ElementIcon key={`${index}`} src={icon} /> : null;
keys aqui tambem

2023-03-18 01:38 UTC, chap0lin commented on src/scenes/Titanic/components/Map/index.tsx
> +  const mapSectors = [];
tá feio mas vida que segue

2023-03-18 01:38 UTC, chap0lin commented on src/scenes/Titanic/components/PlayerCards/index.tsx
> +    icebergStatus = -200;
magic numbers complicam bastante o entendimento. Tu não havias criado um enum com esses valores. usa o enum nesses lugares.

2023-03-18 01:38 UTC, chap0lin commented on src/scenes/Titanic/Game/index.tsx
> +    }
mesma estratégia de inicialização.

2023-03-18 01:38 UTC, chap0lin commented on src/scenes/Titanic/Titanic.tsx
> +};
Esses números deveriam ser traduzidos em algum enum ou const com seus significados.

2023-03-18 01:43 UTC, AmigoDoCarlos commented on src/scenes/SelectNextGame/SelectNextGame.tsx
> +      const newPlayerList = JSON.parse(reply);
done

2023-03-18 01:56 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Finish/index.tsx
> +    setPlaces(initialValues);
done!

2023-03-18 02:54 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Finish/index.tsx
> +  }, [places]);
Done

2023-03-18 13:39 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Finish/index.tsx
> +    gsap
done

2023-03-18 13:40 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Finish/index.tsx
> +  };
não entendi como fazer com que seja só um. Eu preciso que os tempos de aparecimento dos titanics e icebergs sejam consecutivos, não todos de uma vez. É por isso que há vários timeouts.

2023-03-18 13:48 UTC, AmigoDoCarlos commented on src/scenes/Titanic/components/PlayerCards/index.tsx
> +    icebergStatus = -200;
done

2023-03-18 13:51 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Game/index.tsx
> +    }
done

2023-03-18 13:52 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Titanic.tsx
> +};
mas esse já não é o 'enum'? não é explicitamente um enum porque a maioria dos valores são vetores em vez de simples números.

2023-03-18 13:52 UTC, AmigoDoCarlos commented on src/scenes/Titanic/components/Map/Sector/GameMapSector/index.tsx
> +    number >= 100 ? <ElementIcon key={`${index}`} src={icon} /> : null;
done

2023-03-18 14:02 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Finish/index.tsx
> +    setPlaces(initialValues);
A estratégia de inicializar desse modo lançou erros no lint.

2023-03-18 15:51 UTC, AmigoDoCarlos commented on src/scenes/Titanic/Finish/index.tsx
> +    setPlaces(initialValues);
erros corrigidos.

2023-03-18 16:41 UTC, merged